CREATE TABLE IF NOT EXISTS DIM.TEAMS (
    TEAM_ID NUMBER,
    TEAM_NAME STRING,
    TEAM_ABBREV STRING,
    LEAGUE_NAME STRING,
    DIVISION_NAME STRING,
    VENUE_NAME STRING,
    ACTIVE_FLAG BOOLEAN
);

CREATE TABLE IF NOT EXISTS DIM.PLAYERS (
    PLAYER_ID NUMBER,
    FULL_NAME STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    PRIMARY_POSITION STRING,
    BAT_SIDE STRING,
    PITCH_HAND STRING,
    CURRENT_TEAM_ID NUMBER,
    ACTIVE_FLAG BOOLEAN
);