CREATE OR REPLACE TABLE MLB_ANALYTICS.DIM.DATE AS
SELECT
    DATEADD(DAY, SEQ4(), '2020-01-01'::DATE) AS DATE_KEY,
    YEAR(DATE_KEY) AS YEAR,
    MONTH(DATE_KEY) AS MONTH_NUMBER,
    MONTHNAME(DATE_KEY) AS MONTH_NAME,
    DAY(DATE_KEY) AS DAY_OF_MONTH,
    DAYOFWEEKISO(DATE_KEY) AS DAY_OF_WEEK_NUMBER,
    DAYNAME(DATE_KEY) AS DAY_NAME,
    WEEKOFYEAR(DATE_KEY) AS WEEK_NUMBER,
    QUARTER(DATE_KEY) AS QUARTER_NUMBER
FROM TABLE(GENERATOR(ROWCOUNT => 7305));

CREATE TABLE IF NOT EXISTS DIM.TEAMS (
    TEAM_ID NUMBER,
    TEAM_NAME STRING,
    TEAM_ABBREV STRING,
    LEAGUE_NAME STRING,
    DIVISION_NAME STRING,
    VENUE_NAME STRING,
    ACTIVE_FLAG BOOLEAN
);

CREATE TABLE IF NOT EXISTS DIM.PLAYERS (
    PLAYER_ID NUMBER,
    FULL_NAME STRING,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    PRIMARY_POSITION STRING,
    BAT_SIDE STRING,
    PITCH_HAND STRING,
    CURRENT_TEAM_ID NUMBER,
    ACTIVE_FLAG BOOLEAN
);