CREATE OR REPLACE VIEW ANALYTICS.TEAM_DAILY_SUMMARY AS
SELECT
    GAME_DATE,
    HOME_TEAM_ID AS TEAM_ID,
    AWAY_TEAM_ID AS OPPONENT_TEAM_ID,
    HOME_SCORE AS RUNS_SCORED,
    AWAY_SCORE AS RUNS_ALLOWED,
    CASE WHEN HOME_SCORE > AWAY_SCORE THEN 1 ELSE 0 END AS WIN_FLAG
FROM RAW.GAMES

UNION ALL

SELECT
    GAME_DATE,
    AWAY_TEAM_ID AS TEAM_ID,
    HOME_TEAM_ID AS OPPONENT_TEAM_ID,
    AWAY_SCORE AS RUNS_SCORED,
    HOME_SCORE AS RUNS_ALLOWED,
    CASE WHEN AWAY_SCORE > HOME_SCORE THEN 1 ELSE 0 END AS WIN_FLAG
FROM RAW.GAMES;

CREATE OR REPLACE VIEW ANALYTICS.DAILY_HITTER_LEADERS AS
SELECT
    B.GAME_DATE,
    B.PLAYER_ID,
    P.FULL_NAME,
    B.TEAM_ID,
    T.TEAM_ABBREV,
    B.AB,
    B.H,
    B.HR,
    B.RBI,
    B.BB,
    B.OPS,
    (B.HR * 4) + (B.RBI * 2) + B.H + B.BB AS PERFORMANCE_SCORE
FROM RAW.PLAYER_GAME_BATTING B
LEFT JOIN DIM.PLAYERS P
    ON B.PLAYER_ID = P.PLAYER_ID
LEFT JOIN DIM.TEAMS T
    ON B.TEAM_ID = T.TEAM_ID;

CREATE OR REPLACE VIEW ANALYTICS.DAILY_PITCHER_LEADERS AS
SELECT
    S.GAME_DATE,
    S.PLAYER_ID,
    P.FULL_NAME,
    S.TEAM_ID,
    T.TEAM_ABBREV,
    S.IP,
    S.ER,
    S.SO,
    S.BB,
    S.ERA,
    ((S.SO * 2) + (S.IP * 3) - (S.ER * 2) - S.BB) AS PERFORMANCE_SCORE
FROM RAW.PLAYER_GAME_PITCHING S
LEFT JOIN DIM.PLAYERS P
    ON S.PLAYER_ID = P.PLAYER_ID
LEFT JOIN DIM.TEAMS T
    ON S.TEAM_ID = T.TEAM_ID;
