CREATE OR REPLACE VIEW ANALYTICS.TEAM_DAILY_SUMMARY AS
SELECT
    GAME_DATE,
    GAME_ID,
    HOME_TEAM_ID AS TEAM_ID,
    AWAY_TEAM_ID AS OPPONENT_TEAM_ID,
    HOME_SCORE AS RUNS_SCORED,
    AWAY_SCORE AS RUNS_ALLOWED,
    CASE WHEN HOME_SCORE > AWAY_SCORE THEN 1 ELSE 0 END AS WIN_FLAG
FROM RAW.GAMES

UNION ALL

SELECT
    GAME_DATE,
    GAME_ID,
    AWAY_TEAM_ID AS TEAM_ID,
    HOME_TEAM_ID AS OPPONENT_TEAM_ID,
    AWAY_SCORE AS RUNS_SCORED,
    HOME_SCORE AS RUNS_ALLOWED,
    CASE WHEN AWAY_SCORE > HOME_SCORE THEN 1 ELSE 0 END AS WIN_FLAG
FROM RAW.GAMES;

CREATE OR REPLACE VIEW ANALYTICS.DAILY_HITTER_LEADERS AS
WITH deduped AS (
  SELECT *
  FROM RAW.PLAYER_GAME_BATTING
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY GAME_ID, PLAYER_ID
    ORDER BY CREATED_AT DESC
  ) = 1
)
SELECT
  B.GAME_ID,
  B.GAME_DATE,
  B.PLAYER_ID,
  P.FULL_NAME,
  B.TEAM_ID,
  T.TEAM_ABBREV,
  B.AB,
  B.H,
  B.DOUBLES,
  B.TRIPLES,
  B.HR,
  B.RBI,
  B.BB,
  B.OPS,
  (B.HR * 4) + (B.RBI * 2) + B.H + B.BB AS PERFORMANCE_SCORE
FROM deduped B
LEFT JOIN DIM.PLAYERS P ON B.PLAYER_ID = P.PLAYER_ID
LEFT JOIN DIM.TEAMS T ON B.TEAM_ID = T.TEAM_ID;

CREATE OR REPLACE VIEW ANALYTICS.DAILY_PITCHER_LEADERS AS
WITH deduped AS (
  SELECT *
  FROM RAW.PLAYER_GAME_PITCHING
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY GAME_ID, PLAYER_ID
    ORDER BY CREATED_AT DESC
  ) = 1
)
SELECT
    S.GAME_ID,
    S.GAME_DATE,
    S.PLAYER_ID,
    P.FULL_NAME,
    S.TEAM_ID,
    T.TEAM_ABBREV,
    S.IP,
    S.ER,
    S.SO,
    S.BB,
    S.ERA,
    ((S.SO * 2) + (S.IP * 3) - (S.ER * 2) - S.BB) AS PERFORMANCE_SCORE
FROM deduped S
LEFT JOIN DIM.PLAYERS P ON S.PLAYER_ID = P.PLAYER_ID
LEFT JOIN DIM.TEAMS T ON S.TEAM_ID = T.TEAM_ID;

CREATE OR REPLACE VIEW ANALYTICS.GAME_SCOREBOARD AS
SELECT
    g.game_date,
    g.game_id,
    ht.team_abbrev AS home_team_abbrev,
    ht.team_name AS home_team_name,
    at.team_abbrev AS away_team_abbrev,
    at.team_name AS away_team_name,
    g.home_score,
    g.away_score,
    g.winning_pitcher_id,
    g.losing_pitcher_id,
    g.save_pitcher_id,
    g.status,
    g.venue_name,
    g.day_night
FROM RAW.GAMES g
LEFT JOIN DIM.TEAMS ht
    ON g.home_team_id = ht.team_id
LEFT JOIN DIM.TEAMS at
    ON g.away_team_id = at.team_id;

CREATE OR REPLACE VIEW ANALYTICS.FACT_DAILY_LEAGUE_SNAPSHOT AS
WITH game_totals AS (
    SELECT
        GAME_DATE,
        COUNT(*) AS GAMES_PLAYED,
        SUM(HOME_SCORE + AWAY_SCORE) AS TOTAL_RUNS,
        AVG(HOME_SCORE + AWAY_SCORE) AS AVG_RUNS_PER_GAME
    FROM ANALYTICS.FACT_GAME
    GROUP BY GAME_DATE
),

batting_totals AS (
    SELECT
        GAME_DATE,
        SUM(H) AS TOTAL_HITS,
        SUM(HR) AS TOTAL_HOME_RUNS,
        SUM(BB) AS TOTAL_WALKS,
        SUM(SO) AS BATTER_STRIKEOUTS
    FROM ANALYTICS.FACT_PLAYER_GAME_BATTING
    GROUP BY GAME_DATE
),

pitching_totals AS (
    SELECT
        GAME_DATE,
        SUM(SO) AS PITCHER_STRIKEOUTS,
        SUM(PITCHES) AS TOTAL_PITCHES,
        SUM(STRIKES) AS TOTAL_STRIKES
    FROM ANALYTICS.FACT_PLAYER_GAME_PITCHING
    GROUP BY GAME_DATE
)

SELECT
    G.GAME_DATE,
    G.GAMES_PLAYED,
    G.TOTAL_RUNS,
    G.AVG_RUNS_PER_GAME,
    B.TOTAL_HITS,
    B.TOTAL_HOME_RUNS,
    B.TOTAL_WALKS,
    B.BATTER_STRIKEOUTS,
    P.PITCHER_STRIKEOUTS,
    P.TOTAL_PITCHES,
    P.TOTAL_STRIKES
FROM game_totals G
LEFT JOIN batting_totals B
    ON G.GAME_DATE = B.GAME_DATE
LEFT JOIN pitching_totals P
    ON G.GAME_DATE = P.GAME_DATE;
