CREATE SCHEMA IF NOT EXISTS MLB_ANALYTICS.PUBLIC_EXPORT;

CREATE OR REPLACE VIEW MLB_ANALYTICS.PUBLIC_EXPORT.GAMES AS
SELECT
    g.GAME_ID,
    g.GAME_DATE,
    g.SEASON,
    g.GAME_TYPE,
    g.STATUS,
    ht.TEAM_ID AS HOME_TEAM_ID,
    ht.TEAM_NAME AS HOME_TEAM_NAME,
    ht.TEAM_ABBREV AS HOME_TEAM_ABBREV,
    at.TEAM_ID AS AWAY_TEAM_ID,
    at.TEAM_NAME AS AWAY_TEAM_NAME,
    at.TEAM_ABBREV AS AWAY_TEAM_ABBREV,
    g.HOME_SCORE,
    g.AWAY_SCORE,
    g.WINNING_TEAM_ID,
    wt.TEAM_NAME AS WINNING_TEAM_NAME,
    g.LOSING_TEAM_ID,
    lt.TEAM_NAME AS LOSING_TEAM_NAME,
    wp.FULL_NAME AS WINNING_PITCHER_NAME,
    lp.FULL_NAME AS LOSING_PITCHER_NAME,
    sp.FULL_NAME AS SAVE_PITCHER_NAME,
    g.VENUE_NAME,
    g.DAY_NIGHT
FROM MLB_ANALYTICS.ANALYTICS.FACT_GAME g
LEFT JOIN MLB_ANALYTICS.DIM.TEAMS ht
    ON g.HOME_TEAM_ID = ht.TEAM_ID
LEFT JOIN MLB_ANALYTICS.DIM.TEAMS at
    ON g.AWAY_TEAM_ID = at.TEAM_ID
LEFT JOIN MLB_ANALYTICS.DIM.TEAMS wt
    ON g.WINNING_TEAM_ID = wt.TEAM_ID
LEFT JOIN MLB_ANALYTICS.DIM.TEAMS lt
    ON g.LOSING_TEAM_ID = lt.TEAM_ID
LEFT JOIN MLB_ANALYTICS.DIM.PLAYERS wp
    ON g.WINNING_PITCHER_ID = wp.PLAYER_ID
LEFT JOIN MLB_ANALYTICS.DIM.PLAYERS lp
    ON g.LOSING_PITCHER_ID = lp.PLAYER_ID
LEFT JOIN MLB_ANALYTICS.DIM.PLAYERS sp
    ON g.SAVE_PITCHER_ID = sp.PLAYER_ID
ORDER BY g.GAME_DATE DESC, g.GAME_ID DESC;

CREATE OR REPLACE VIEW MLB_ANALYTICS.PUBLIC_EXPORT.TEAM_GAME AS
SELECT
    tg.GAME_ID,
    tg.GAME_DATE,
    tg.TEAM_ID,
    team.TEAM_NAME,
    team.TEAM_ABBREV,
    tg.OPPONENT_TEAM_ID,
    opp.TEAM_NAME AS OPPONENT_NAME,
    opp.TEAM_ABBREV AS OPPONENT_ABBREV,
    tg.HOME_AWAY,
    tg.RUNS_SCORED,
    tg.RUNS_ALLOWED,
    tg.RUN_DIFFERENTIAL,
    tg.WIN_FLAG,
    CASE WHEN tg.WIN_FLAG = 1 THEN 0 ELSE 1 END AS LOSS_FLAG,
    tg.TEAM_GAME_COUNT
FROM MLB_ANALYTICS.ANALYTICS.FACT_TEAM_GAME tg
LEFT JOIN MLB_ANALYTICS.DIM.TEAMS team
    ON tg.TEAM_ID = team.TEAM_ID
LEFT JOIN MLB_ANALYTICS.DIM.TEAMS opp
    ON tg.OPPONENT_TEAM_ID = opp.TEAM_ID
ORDER BY tg.GAME_DATE DESC, tg.GAME_ID DESC, tg.TEAM_ID;

CREATE OR REPLACE VIEW MLB_ANALYTICS.PUBLIC_EXPORT.BATTING AS
SELECT
    b.GAME_ID,
    b.GAME_DATE,
    b.PLAYER_ID,
    p.FULL_NAME AS PLAYER_NAME,
    b.TEAM_ID,
    t.TEAM_NAME,
    t.TEAM_ABBREV AS TEAM_ABBREV,
    t.LEAGUE_NAME AS LEAGUE,
    t.DIVISION_NAME AS DIVISION,
    b.POSITION_CODE AS POSITION,
    b.AB AS AT_BATS,
    b.H AS HITS,
    b.R AS RUNS,
    b.DOUBLES,
    b.TRIPLES,
    b.HR AS HOME_RUNS,
    b.RBI,
    b.BB AS WALKS,
    b.SO AS STRIKEOUTS,
    b.HBP AS HIT_BY_PITCH,
    b.SB AS STOLEN_BASES,
    b.CS AS CAUGHT_STEALING,
    b.AVG,
    b.OBP,
    b.SLG,
    b.OPS,
    b.PERFORMANCE_SCORE
FROM MLB_ANALYTICS.ANALYTICS.FACT_PLAYER_GAME_BATTING b
LEFT JOIN MLB_ANALYTICS.DIM.PLAYERS p
    ON b.PLAYER_ID = p.PLAYER_ID
LEFT JOIN MLB_ANALYTICS.DIM.TEAMS t
    ON b.TEAM_ID = t.TEAM_ID
ORDER BY b.GAME_DATE DESC, b.GAME_ID DESC, b.PLAYER_ID;

CREATE OR REPLACE VIEW MLB_ANALYTICS.PUBLIC_EXPORT.PITCHING AS
SELECT
    p.GAME_ID,
    p.GAME_DATE,
    p.PLAYER_ID,
    pl.FULL_NAME AS PLAYER_NAME,
    p.TEAM_ID,
    t.TEAM_NAME,
    t.TEAM_ABBREV AS TEAM_ABBREV,
    t.LEAGUE_NAME AS LEAGUE,
    t.DIVISION_NAME AS DIVISION,
    p.IP AS INNINGS_PITCHED,
    p.H_ALLOWED AS HITS_ALLOWED,
    p.R_ALLOWED AS RUNS_ALLOWED,
    p.ER AS EARNED_RUNS,
    p.BB AS WALKS,
    p.SO AS STRIKEOUTS,
    p.HR_ALLOWED AS HOME_RUNS_ALLOWED,
    p.PITCHES,
    p.STRIKES,
    p.DECISION,
    p.ERA,
    p.WHIP,
    p.PERFORMANCE_SCORE
FROM MLB_ANALYTICS.ANALYTICS.FACT_PLAYER_GAME_PITCHING p
LEFT JOIN MLB_ANALYTICS.DIM.PLAYERS pl
    ON p.PLAYER_ID = pl.PLAYER_ID
LEFT JOIN MLB_ANALYTICS.DIM.TEAMS t
    ON p.TEAM_ID = t.TEAM_ID
ORDER BY p.GAME_DATE DESC, p.GAME_ID DESC, p.PLAYER_ID;
